Problema 35 arey
AleixMT/Problemas-Computadores pull request #25
Opened 2022-12-07 18:02 UTC by AreyFerreroRamos

Errores y deficiencias en el problema 35 solucionadas.

2022-12-07 18:16 UTC, AleixMT requested changes
El archivo `activar_beat.txt.txt` tiene la extensión dos veces. Puedes ponerla solo una vez?

2022-12-07 18:16 UTC, AleixMT commented on 35/activar_beat.txt.txt
> +A continuación se ofrece una recopilación de las conclusiones que se deben ir extrayendo, a partir de la información
Puedes renombrar este archivo `activar_beat.txt.txt` a `activar_beat.txt`?

2022-12-08 11:01 UTC, AreyFerreroRamos commented
Correcciones hechas. Subido al repositorio remoto como podrás ver desde el gitk. No obstante, tengo dudas sobre que hacer ahora. ¿Cierro la pull request con este comentario?

2022-12-08 11:04 UTC, AreyFerreroRamos commented
Sabes que, me la juego y del error se aprende.

2022-12-08 11:28 UTC, AreyFerreroRamos commented
Solucionando problemas al hacer mal el pull request

2022-12-08 12:31 UTC, AleixMT commented
Cuando terminas tus cambios, tienes que pedir una review para hacer el merge

2022-12-08 12:37 UTC, AleixMT commented
Tienes dos cosas que hacer:
- Solucionar conflictos al fusionar con la rama `master`. Tienes que ir a la última versión de `problema_35_arey` y fusionarte contra el master en tu propia rama `git pull origin master`. Resuelve conflictos y pushea los cambios con `git push origin problema_35_arey`. Entonces el merge estará disponible sin conflictos.
- Te he hecho un **Request changes** de tus cambios. Cámbiale la extensión de ese `.txt` a `.md` ya que estás usando formato ligero y para tal fin existe markdown. 

![image](https://user-images.githubusercontent.com/23342150/206447000-3e0c3907-75ed-4ce9-afd8-b9059a07165f.png)

2022-12-08 13:19 UTC, AreyFerreroRamos commented
Ya he logrado solucionar los conflictos. Como verás, sólo queda que me apruebes la PR. No he cambiado la extensión del fichero 'activar_beat' porque hay algún tipo de problema con las extensiones (has podido verlo anteriormente). Una vez hayas aprobado la PR puedes cambiarlo a tu gusto.

2022-12-08 13:52 UTC, AleixMT approved these changes
Aprobamos y ya cambiaremos la extensión.

2022-12-08 13:53 UTC, merged