Problema 19 arey
AleixMT/Problemas-Computadores pull request #48
Opened 2022-12-24 12:04 UTC by AreyFerreroRamos

Aquí está la solució del problema 19 propuesta por el Dr Santiago Romaní Also.

2022-12-24 12:54 UTC, AleixMT requested changes
Perfect 👍 . Ahora solo falta que modifiques la línea del `README.md` para añadir los enlaces y cambiar el estado de solución. Puedes mirar cualquier otro problema resuelto como ejemplo. Si no te sale algo avisa.

2022-12-24 13:37 UTC, AreyFerreroRamos commented
Ja está hecha la modificación de la línea del README.md correspondiente al problema 19 para añadir los enlaces y cambiar el estado de la solución.

2022-12-24 13:55 UTC, AleixMT commented
Por favor usa un IDE capaz de renderizar markdown (cualquiera de Jetbrains) o la propia interfície de GitHub para revisar que el `README.md` se ve correctamente. Con ese último cambio has roto la tabla sin querer:

![image](https://user-images.githubusercontent.com/23342150/209438826-1ce41540-9f7f-42f4-9b0e-cd8ed67d2eb9.png)

Faltan los guiones en las columnas vacías, igual que en las demás soluciones y los links de acceso a la rutina `inicializar_timer01.s`, que se puede considerar un requerimiento especial. Presupongo que lo análogo para #49

2022-12-24 13:55 UTC, AleixMT requested changes
Cambios en `README.md`

2022-12-24 15:34 UTC, AreyFerreroRamos commented
En principio, la tabla ya no está rota.

2022-12-24 15:48 UTC, AreyFerreroRamos commented
Me había olvidado del guión. Ahora sí que creo que está todo.

2022-12-29 14:49 UTC, AleixMT requested changes
Requiero más cambios:
- Lo mismo que en #49 : La tabla no esta alineada
![image](https://user-images.githubusercontent.com/23342150/209969463-bb4fd8f2-0749-4a46-a740-43772b21de9e.png)

- Falta situar las variables globales en C como requerimiento especial.

Puedes mirar cualquiera de los demás problemas y seguir el ejemplo.

2022-12-29 21:09 UTC, AreyFerreroRamos commented
Aleix, no entiendo a que te refieres con que la tabla no está alineada. Cuando abro el README.md con el editor del github no veo nada que esté fuera de lugar. No puedo solucionar un error que no veo.

2022-12-29 21:17 UTC, AleixMT commented
No me refiero al renderizado, sino al texto. He adjuntado una captura donde se ve tu línea no alineada con el resto

2022-12-29 21:57 UTC, AreyFerreroRamos commented
Sí. He entendido que te referías al texto y he observado la imagen que es adjuntado. Pero al editar el fichero README.md con el editor del github el texto parece estar correctamente alineado. 
![Captura](https://user-images.githubusercontent.com/79418600/210014842-752cbfc4-19c5-46fc-980d-97d8328d1da8.PNG)

2022-12-29 22:03 UTC, AreyFerreroRamos commented
He provado una cosa, aunque no tengo demasiadas esperanzas de que funcione. Por otro lado, las variables en c ya están situadas como requerimiento especial.

2022-12-29 22:30 UTC, AleixMT commented
> Sí. He entendido que te referías al texto y he observado la imagen que es adjuntado. Pero al editar el fichero README.md con el editor del github el texto parece estar correctamente alineado. 
> ![Captura](https://user-images.githubusercontent.com/79418600/210014842-752cbfc4-19c5-46fc-980d-97d8328d1da8.PNG)
> 

Fijate que la línea 28 y 29 son una sola línea pero tienen una anchura diferente. Eso no tiene sentido en un archivo de texto plano donde cada línea ocupa exactamente eso: una línea. 

Este editor de texto te hace line breaks automáticamente por lo que no puedes ver si están alineadas o no. Usa otro que no te haga line breaks automáticamente

2022-12-29 22:33 UTC, AleixMT commented
> He provado una cosa, aunque no tengo demasiadas esperanzas de que funcione. Por otro lado, las variables en c ya están situadas como requerimiento especial.

¿Qué has probado?

2022-12-29 22:36 UTC, AreyFerreroRamos commented
He probado a tabular un '|-|' hasta alinearlo con el de la línea superior. Ya te digo, no creo que funcione.

2022-12-29 22:37 UTC, AreyFerreroRamos commented
Bueno, sólo ha quedado el error relacionado con el texto desalineado.

2022-12-30 13:28 UTC, AleixMT commented
Voy a añadir commits en `[problema_19_arey](https://github.com/AleixMT/Problemas-Computadores/tree/problema_19_arey)`.

2022-12-30 13:31 UTC, AleixMT approved these changes

2022-12-30 13:32 UTC, merged