Problema 8 arey
AleixMT/Problemas-Computadores pull request #49
Opened 2022-12-24 13:03 UTC by AreyFerreroRamos

Aquí tienes la solución que propongo para el problema 8. He añadido una rutina adicional que es llamada desde una de las rutinas que se tiene que implementar (diseño descendente)

2022-12-24 13:33 UTC, AleixMT requested changes
Vale, yo lo veo bien pero falta lo mismo que en #48 : Actualizar el estado del `README.md` y los enlaces a los diferentes archivos de solución.

2022-12-24 13:52 UTC, AreyFerreroRamos commented
Ya he modificado la línea del README.md correspondiente al problema 8 para añadir los enlaces y para cambiar el estado de la solución.

2022-12-24 13:59 UTC, AleixMT requested changes
![image](https://user-images.githubusercontent.com/23342150/209439072-1a79226b-0586-477d-ad1d-cdb9e4caa67c.png)

Tabla rota para los cambios del problema 8. Usa GitHub o un renderizador de markdown (CLion?) para ver que lo has hecho bien.

2022-12-24 13:59 UTC, AleixMT commented on README.md
> +																																																															| `insertar_strings.c` [👁️](https://github.com/AleixMT/Problemas-Computadores/blob/master/Soluciones/08/insertar_strings.s) [📥](https://
Te faltan columnas y por eso la visualización de la tabla se rompe. Sigue el ejemplo de las demás lineas, usa el mismo espaciado y patrón y no fallarás.

2022-12-24 14:05 UTC, AleixMT commented
Añade los requerimientos de cada problema como enlaces a los archivos de la solución en la tabla. Fijate que ahora todo lo que se pide en el enunciado está enlazado y clasificado en cada columna

2022-12-24 14:08 UTC, AleixMT commented
La idea es que lo que se pide en la última frase de los enunciados aparezca en cada fila de la tabla con enlaces. Hay 4 tipos de requerimientos. Mírate el 20 que tiene un poco de todo.

2022-12-24 15:51 UTC, AreyFerreroRamos commented
Ahora ya sí que está todo, a mi parecer. Todos los problemas han sido consecuencia de editar el fichero README.md desde el bloc de notas. Con el editor de GitHub ha sido todo mucho más sencillo.

2022-12-29 14:35 UTC, AleixMT requested changes
Requiero cambios:
- `insertar_string.c` no existe, es `.s`
- `insertar_string.s` es una función en assembler, no es un requerimiento especial
- Variables globales en C **sí** es un requerimiento especial
- La linea 18 está mal alineada con respecto a los separadores de la tabla. Alineala sinó luego hacer cambios en la tabla es un galimatías:
![image](https://user-images.githubusercontent.com/23342150/209967752-b8d7c887-889f-434c-91bb-22b4abcfeba9.png)
- La visualización del enunciado 8 está rota, así como el resto de visualizaciones de los enunciados por debajo del 10. Parece que le falta un '0' en el link. Te diría que los arreglases, pero arreglar el del enunciado 8 es lo único necesario en esta PR. Haz lo que consideres.

2022-12-29 21:34 UTC, AreyFerreroRamos commented
He cambiado las extensiones de las rutinas insertar_strings e insertar_string de '.c' a '.s', he trasladado la rutina insertar_string.s al camp 'función en assembler' y he añadido las variables globales al campo requerimiento especial.

2022-12-29 21:41 UTC, AreyFerreroRamos commented
Desde la visualización del editor del github no aprecio que la tabla no esté alineada. No puedo corregirlo si no veo el error.
![Captura](https://user-images.githubusercontent.com/79418600/210013644-f09b339e-a78b-43ef-ad97-77ee755a627f.PNG)

2022-12-29 21:42 UTC, AreyFerreroRamos commented
Podría ir probando a ver si acierto, pero no creo que tenga mucho sentido dar palos de ciego.

2022-12-29 21:53 UTC, AreyFerreroRamos commented
Por último, no entiendo el último cambio que requieres. ¿A qué te refieres con que la visualización del enunciado 8 está rota? Lo que yo veo, a priori, parece completo. He estado revisando los enlaces del problema 8 (comparándolos con los del problema 7) y no detecto la ausencia de ningún 0. Lamento no ser capaz de detectar el error en esta primera toma de contacto.

2022-12-29 22:07 UTC, AleixMT commented
> Desde la visualización del editor del github no aprecio que la tabla no esté alineada. No puedo corregirlo si no veo el error.
> ![Captura](https://user-images.githubusercontent.com/79418600/210013644-f09b339e-a78b-43ef-ad97-77ee755a627f.PNG)
> 
> 

Este editor te hace *line break* automáticamente, por lo que si tienes suficiente texto en una línea te la pasa a la siguiente línea, por lo que no puedes ver la parte desalineada de la tabla.

Usa un editor de texto plano que no te haga line breaks. Por ejemplo el Notepad de Windows, `nano`, `gedit`, `vim`... 

Bueno, si no te sale ya lo haré yo, no te preocupes.

2022-12-29 22:15 UTC, AreyFerreroRamos commented
Estoy usando el editor vim, pero el texto también me aparece alineado.
![Captura](https://user-images.githubusercontent.com/79418600/210016079-e2cca2f6-ae00-4e08-9d54-807b12cd72df.PNG)

2022-12-29 22:16 UTC, AleixMT commented
> Por último, no entiendo el último cambio que requieres. ¿A qué te refieres con que la visualización del enunciado 8 está rota? Lo que yo veo, a priori, parece completo. He estado revisando los enlaces del problema 8 (comparándolos con los del problema 7) y no detecto la ausencia de ningún 0. Lamento no ser capaz de detectar el error en esta primera toma de contacto. 

Me refiero a que el enlace está roto. Si haces click en el ojo para ver el enunciado verás que no dirige a ningún sitio (404 Not found). El enlace válido lleva un 0 extra delante.

2022-12-29 22:22 UTC, AreyFerreroRamos commented
¿No sería al revés? ¿Que lo que ocurre es que le sobra un 0?

2022-12-29 22:33 UTC, AreyFerreroRamos commented
Nada. No hagas caso del último comentario. Ya están arregladas las visualizaciones de los enunciados de los problemas por debajo del 10.

2022-12-29 22:35 UTC, AreyFerreroRamos commented
Lo único que no he conseguido arreglar es el error relacionadocon el texto desalineado.

2022-12-29 22:39 UTC, AleixMT commented
> Estoy usando el editor vim, pero el texto también me aparece alineado.
> ![Captura](https://user-images.githubusercontent.com/79418600/210016079-e2cca2f6-ae00-4e08-9d54-807b12cd72df.PNG)
> 

Te está haciendo line breaks automáticos. Usa un editor de texto gráfico. Gedit (?)

2022-12-30 10:51 UTC, AreyFerreroRamos commented
Dado que no tengo el gedit instalado en el ordenador desde el que administro este repositorio, he accedido a la milax (que tengo instalada en otro ordenador) la cual lleva el gedit instalado por defecto y me he clonado este repositorio allí. Por desgracia, ha sido en vano, ya que el gedit también me hace line breaks automáticamente. También he provado a usar los editores vi, vim y nano desde la milax y todos me hacen line breaks automáticamente. Dado que soy incapaz de, con ninguna de las herramientas que tengo a mi disposición, alinear el texto, te pido si podrías aprobarme la PR y alinear el texto tú. Al menos parece que he podido solucionar todos los demás errores.

2022-12-30 11:09 UTC, AreyFerreroRamos commented
Dado que no tengo el gedit instalado en el ordenador desde el que administro este repositorio, he accedido a la milax (que tengo instalada en otro ordenador) la cual lleva el gedit instalado por defecto y me he clonado este repositorio allí. Por desgracia, ha sido en vano, ya que el gedit también me hace line breaks automáticamente. También he provado a usar los editores vi, vim y nano desde la milax y todos me hacen line breaks automáticamente.

He probado también a instalar un IDE de JetBrains, en concreto el PyCharm, en el ordenador desde el que administro este repositorio. No obstante, también me hace line breaks automáticos. Te adjunto una imagen.
![Captura](https://user-images.githubusercontent.com/79418600/210063561-67b9fdb4-348c-4567-bccb-151f6adee971.PNG)

La verdad es que ya no se que más probar dado que soy incapaz de alinear el texto con ninguna de estas herramientas así que te pido si podrías aprobarme la PR y alinear tú el texto. Al menos el resto de errores están solucionados.

2022-12-30 11:12 UTC, AreyFerreroRamos commented
Para evitar confusiones con el contenido de la imagen, creo que debo aclarar que aunque este diálogo está ocurriendo dentro de la PR del problema 8, las pruebas que he comentado en el comentario anterior las he hecho en la rama correspondiente al problema 19 (en la que estoy teniendo que afrontar el mismo problema de texto desalineado). Disculpa la confusión que esto pueda llegar a ocasionar.

2022-12-30 13:25 UTC, AleixMT commented
> Dado que no tengo el gedit instalado en el ordenador desde el que administro este repositorio, he accedido a la milax (que tengo instalada en otro ordenador) la cual lleva el gedit instalado por defecto y me he clonado este repositorio allí. Por desgracia, ha sido en vano, ya que el gedit también me hace line breaks automáticamente. También he provado a usar los editores vi, vim y nano desde la milax y todos me hacen line breaks automáticamente.

En `gedit` tienes que desactivar el *line break* o *line wrap* en preferencias.

![image](https://user-images.githubusercontent.com/23342150/210074751-67060a61-b511-4ef6-a781-3120f3945401.png)

![image](https://user-images.githubusercontent.com/23342150/210074773-2124f121-e7ed-4a8f-b299-d740bea94f78.png)


> He probado también a instalar un IDE de JetBrains, en concreto el PyCharm, en el ordenador desde el que administro este repositorio. No obstante, también me hace line breaks automáticos. Te adjunto una imagen. ![Captura](https://user-images.githubusercontent.com/79418600/210063561-67b9fdb4-348c-4567-bccb-151f6adee971.PNG)

No te está haciendo ningún *line break* automático. Se ve en la foto. De hecho, yo uso PyCharm para editar la tabla.

> La verdad es que ya no se que más probar dado que soy incapaz de alinear el texto con ninguna de estas herramientas así que te pido si podrías aprobarme la PR y alinear tú el texto. Al menos el resto de errores están solucionados.

Okey 👍 , no worries

2022-12-30 13:35 UTC, AleixMT approved these changes

2022-12-30 13:35 UTC, merged