Arey: Añadido de líneas en blanco y de comentarios al main y a las RSIs del problema 17.
AleixMT/Problemas-Computadores pull request #53
Opened 2023-02-01 19:14 UTC by AreyFerreroRamos

2023-02-03 11:17 UTC, AleixMT commented
De acuerdo, todo bien. Ten en cuenta lo que dije el otro dia en el issue:

> Que las lineas de comentarios no sigan una tabulación estricta es directamente culpa de quien haya tabulado incorrectamente los comentarios. También tiene que ver con indentar usando tabuladores, desconociendo que los tabuladores NUNCA deben usarse para esto puesto que el número de espacios que ocupa un tabulador en pantalla no es fijo.

Entiende que los comentarios siempre van a verse desalineados en diferentes editores de texto si usas tabuladores para el indent. Por favor, no lo hagas.

2023-02-03 11:20 UTC, AleixMT reviewed
Si puedes pásale un _buscar y reemplazar_ al código y reemplaza un tabulador por la medida de espacios que considerabas en tu editor en el momento de hacer el problema (suelen ser 4). 

Si no sabes cómo avísame y ya lo haré yo.

2023-02-03 11:21 UTC, AleixMT requested changes
Si puedes pásale un buscar y reemplazar al código y reemplaza un tabulador por la medida de espacios que considerabas en tu editor en el momento de hacer el problema (suelen ser 4).

Si no sabes cómo avísame y ya lo haré yo.

2023-02-03 15:19 UTC, AreyFerreroRamos commented
No conozco ningún buscar y remplazar código. Si dices que te ofreces a hacerlo tú, yo lo preferiría, sí.

2023-02-03 17:50 UTC, AreyFerreroRamos commented
Ya he sustituido todos los tabuladores por cuatro espacios en blanco

2023-02-07 10:52 UTC, AleixMT approved these changes

2023-02-07 10:52 UTC, merged